# Generated by Django 3.2.11 on 2022-04-21 18:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50)),
                ('product_name', models.CharField(default='', max_length=300)),
                ('link', models.URLField(max_length=500)),
                ('curr_price', models.IntegerField()),
                ('old_price', models.IntegerField()),
                ('website', models.CharField(max_length=10)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
